import {APP_VERSION,DEFAULT_PROMPT,MODELS} from './models.js';
import {hashBlobStreaming,hashText} from './hash.js';
import {inspectAndChunkMp3,materializeChunk,MP3_CHUNKER_REVISION} from './mp3.js';
import {checkpointId,loadCheckpoint,saveCheckpoint,settingsIdentity} from './checkpoint.js';
import {compatibleCheckpoint} from './checkpoint-identity.js';
import {buildFileOutput,downloadText,safeBaseName,safeDisplayName} from './output.js';
import {normalizeOpenAiResult} from './transcript-result.js';
import {ambiguousPaidFailure,automaticRetryDelayMs,checkpointAttemptNeedsConfirmation,completedResultValidationError,knownSafeRetry,systemicJobFailure} from './retry-policy.js';
import {finalPrompt,truncateUtf16Safe} from './text-bounds.js';
import {MAX_COMBINED_FILES,MAX_QUEUE_FILES,combinedExportComplete,combinedExportHasMixedSettings,eligibleQueueItem,preparedQueueItem} from './queue-policy.js';
import {addTranscriptCharacters,combinedTranscriptWithinLimit} from './transcript-limits.js';
import {checkpointResultReusable} from "./retry-policy.js"; // CTW_CHECKPOINT_REUSE_BINDING
// CTW_RESTORED_PROMPT_BOUND
{
  const ctwPreferencesKey = "cosmic-transcriber-web-preferences-v1";
  const ctwClampPreferenceText = (element, value, fallbackMax) => {
    const raw = typeof value === "string" ? value : "";
    const max = Number.isInteger(element?.maxLength) && element.maxLength > 0 ? element.maxLength : fallbackMax;
    let bounded = raw.length > max ? raw.slice(0, max) : raw;
    if (bounded.length && raw.length > bounded.length) {
      const last = bounded.charCodeAt(bounded.length - 1);
      if (last >= 0xD800 && last <= 0xDBFF) bounded = bounded.slice(0, -1);
    }
    return bounded;
  };
  const ctwPromptInput = document.getElementById("promptInput");
  const ctwKeywordsInput = document.getElementById("keywordsInput");
  try {
    const ctwSavedRaw = localStorage.getItem(ctwPreferencesKey);
    if (ctwSavedRaw !== null) {
      const ctwParsed = JSON.parse(ctwSavedRaw);
      if (ctwParsed && typeof ctwParsed === "object" && !Array.isArray(ctwParsed)) {
        let ctwChanged = false;
        if (typeof ctwParsed.prompt === "string") {
          const ctwPromptBounded = ctwClampPreferenceText(ctwPromptInput, ctwParsed.prompt, 12000);
          if (ctwPromptBounded !== ctwParsed.prompt) {
            ctwParsed.prompt = ctwPromptBounded;
            ctwChanged = true;
          }
        }
        if (typeof ctwParsed.keywords === "string") {
          const ctwKeywordsBounded = ctwClampPreferenceText(ctwKeywordsInput, ctwParsed.keywords, 8000);
          if (ctwKeywordsBounded !== ctwParsed.keywords) {
            ctwParsed.keywords = ctwKeywordsBounded;
            ctwChanged = true;
          }
        }
        if (ctwChanged) localStorage.setItem(ctwPreferencesKey, JSON.stringify(ctwParsed));
      }
    }
  } catch {}
  if (ctwPromptInput) ctwPromptInput.value = ctwClampPreferenceText(ctwPromptInput, ctwPromptInput.value, 12000);
  if (ctwKeywordsInput) ctwKeywordsInput.value = ctwClampPreferenceText(ctwKeywordsInput, ctwKeywordsInput.value, 8000);
}

const $=id=>document.getElementById(id);
const UI={appStatus:$('appStatus'),themeBtn:$('themeBtn'),aboutBtn:$('aboutBtn'),aboutDialog:$('aboutDialog'),closeAboutBtn:$('closeAboutBtn'),
 keyStatus:$('keyStatus'),configureKeyBtn:$('configureKeyBtn'),testKeyBtn:$('testKeyBtn'),forgetKeyBtn:$('forgetKeyBtn'),keyDialog:$('keyDialog'),keyForm:$('keyForm'),apiKeyInput:$('apiKeyInput'),keyDialogError:$('keyDialogError'),cancelKeyBtn:$('cancelKeyBtn'),closeKeyBtn:$('closeKeyBtn'),
 addFilesBtn:$('addFilesBtn'),clearQueueBtn:$('clearQueueBtn'),fileInput:$('fileInput'),dropZone:$('dropZone'),queueEmpty:$('queueEmpty'),queueList:$('queueList'),
 modelSelect:$('modelSelect'),modelHelp:$('modelHelp'),languageInput:$('languageInput'),chunkRange:$('chunkRange'),chunkLabel:$('chunkLabel'),durationRange:$('durationRange'),durationLabel:$('durationLabel'),retrySelect:$('retrySelect'),keywordsInput:$('keywordsInput'),promptInput:$('promptInput'),previousContext:$('previousContext'),includeTimestamps:$('includeTimestamps'),exportTxt:$('exportTxt'),exportMd:$('exportMd'),mergeFiles:$('mergeFiles'),continueOnError:$('continueOnError'),costEstimate:$('costEstimate'),
 startBtn:$('startBtn'),cancelBtn:$('cancelBtn'),progressTitle:$('progressTitle'),progressPercent:$('progressPercent'),progressBar:$('progressBar'),progressDetail:$('progressDetail'),fileCountStat:$('fileCountStat'),durationStat:$('durationStat'),completedStat:$('completedStat'),downloads:$('downloads'),downloadButtons:$('downloadButtons'),diagnosticsBtn:$('diagnosticsBtn'),versionText:$('versionText'),
 confirmDialog:$('confirmDialog'),confirmText:$('confirmText'),confirmYes:$('confirmYes'),confirmNo:$('confirmNo')};

const DEFAULTS={theme:'night',model:'gpt-transcribe',languages:'',chunkMb:20,maxMinutes:5,retryCount:0,keywords:'',prompt:DEFAULT_PROMPT,previousContext:true,includeTimestamps:true,exportTxt:true,exportMd:true,mergeFiles:false,continueOnError:true};
const PREF_KEY='cosmic-transcriber-web-preferences-v1';
const state={queue:[],keyConfigured:false,keyExpiresAt:null,principalScope:null,running:false,cancelRequested:false,abort:null,completedFiles:0,downloads:[],diagnostics:[],online:navigator.onLine,confirmResolver:null};

function nowIso(){return new Date().toISOString()}
function rid(prefix){const b=new Uint8Array(12);crypto.getRandomValues(b);return `${prefix}-${Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}`}
function secondsText(sec){sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function money(n){return `$${Number(n||0).toFixed(n<0.01&&n>0?4:2)}`}
function setStatus(text,kind='neutral'){UI.appStatus.textContent=text;UI.appStatus.className=`pill ${kind}`}
function setProgress(percent,title,detail){const p=Math.max(0,Math.min(100,Number(percent)||0));UI.progressBar.value=p;UI.progressPercent.textContent=`${Math.round(p)}%`;if(title!=null)UI.progressTitle.textContent=title;if(detail!=null)UI.progressDetail.textContent=detail}
function addDiag(category,data={}){const safe={time:nowIso(),category};for(const [k,v] of Object.entries(data)){if(/key|authorization|cookie|prompt|transcript|audio|filename|email|token/i.test(k))continue;const s=typeof v==='string'?v.slice(0,240):v;safe[k]=s}state.diagnostics.push(safe);if(state.diagnostics.length>500)state.diagnostics.shift()}
function safeError(error){if(error&&typeof error==='object'){return String(error.message||error.code||'Unexpected error').slice(0,500)}return String(error||'Unexpected error').slice(0,500)}
function errorCode(error){return error?.code||'unknown_error'}

function prefString(value,fallback,max){return typeof value==='string'?truncateUtf16Safe(value,max):fallback}
function prefNumber(value,fallback,min,max){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function prefBool(value,fallback){return typeof value==='boolean'?value:fallback}
function strictUiNumber(value,min,max,{integer=false,label='Numeric setting'}={}){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw new Error(`${label} is outside its supported range.`);return n}
function loadPrefs(){try{const raw=JSON.parse(localStorage.getItem(PREF_KEY)||'{}');if(!raw||typeof raw!=='object'||Array.isArray(raw))return {...DEFAULTS};return {theme:raw.theme==='paper'?'paper':'night',model:MODELS[raw.model]?raw.model:DEFAULTS.model,languages:prefString(raw.languages,'',128),chunkMb:prefNumber(raw.chunkMb,DEFAULTS.chunkMb,5,24),maxMinutes:prefNumber(raw.maxMinutes,DEFAULTS.maxMinutes,3,5),retryCount:prefNumber(raw.retryCount,DEFAULTS.retryCount,0,3),keywords:prefString(raw.keywords,'',8000),prompt:prefString(raw.prompt,DEFAULT_PROMPT,12000),previousContext:prefBool(raw.previousContext,DEFAULTS.previousContext),includeTimestamps:prefBool(raw.includeTimestamps,DEFAULTS.includeTimestamps),exportTxt:prefBool(raw.exportTxt,DEFAULTS.exportTxt),exportMd:prefBool(raw.exportMd,DEFAULTS.exportMd),mergeFiles:prefBool(raw.mergeFiles,DEFAULTS.mergeFiles),continueOnError:prefBool(raw.continueOnError,DEFAULTS.continueOnError)}}catch{return {...DEFAULTS}}}
function savePrefs(){try{const s=readSettings(false);const p={theme:document.documentElement.dataset.theme,model:s.model,languages:UI.languageInput.value,chunkMb:s.chunkMb,maxMinutes:s.maxMinutes,retryCount:s.retryCount,keywords:UI.keywordsInput.value,prompt:UI.promptInput.value,previousContext:s.previousContext,includeTimestamps:s.includeTimestamps,exportTxt:s.exportTxt,exportMd:s.exportMd,mergeFiles:s.mergeFiles,continueOnError:s.continueOnError};localStorage.setItem(PREF_KEY,JSON.stringify(p))}catch{}}
function initSettings(){const p=loadPrefs();document.documentElement.dataset.theme=p.theme==='paper'?'paper':'night';UI.themeBtn.textContent=p.theme==='paper'?'Cosmic Night':'Cosmic Paper';for(const [id,m] of Object.entries(MODELS)){const o=document.createElement('option');o.value=id;o.textContent=m.label;UI.modelSelect.append(o)}UI.modelSelect.value=MODELS[p.model]?p.model:'gpt-transcribe';UI.languageInput.value=p.languages||'';UI.chunkRange.value=String(Math.min(24,Math.max(5,p.chunkMb||20)));UI.durationRange.value=String(Math.min(5,Math.max(3,p.maxMinutes||5)));UI.retrySelect.value=String(Math.min(3,Math.max(0,p.retryCount||0)));UI.keywordsInput.value=p.keywords||'';UI.promptInput.value=p.prompt||DEFAULT_PROMPT;UI.previousContext.checked=p.previousContext!==false;UI.includeTimestamps.checked=p.includeTimestamps!==false;UI.exportTxt.checked=p.exportTxt!==false;UI.exportMd.checked=p.exportMd!==false;UI.mergeFiles.checked=!!p.mergeFiles;UI.continueOnError.checked=p.continueOnError!==false;syncSettingsUi()}
const GPT_TRANSCRIBE_REGIONAL_LANGUAGE_CODES=new Set(['zh-cn','zh-tw','zh-hk']);
function validLanguageCode(code,model){return model==='gpt-transcribe'?(/^[a-z]{2,3}$/.test(code)||GPT_TRANSCRIBE_REGIONAL_LANGUAGE_CODES.has(code)):/^[a-z]{2}$/.test(code)}
function languageList(raw,model,mode){let out=String(raw||'').split(/[\s,;]+/).map(x=>x.trim().toLowerCase()).filter(Boolean);out=[...new Set(out)];if(mode==='none')return [];if(mode==='single'&&out.length>1)throw new Error('The selected model accepts only one language hint.');if(out.length>16)throw new Error('Use no more than 16 language hints.');for(const x of out)if(!validLanguageCode(x,model))throw new Error(model==='gpt-transcribe'?'Use ISO 639-1 codes, supported ISO 639-3 codes, or zh-cn/zh-tw/zh-hk.':'Use a two-letter ISO 639-1 language code such as en or zh.');return out}
function keywordList(raw){const out=[],seen=new Set();let total=0;for(const line of String(raw||'').split(/\n/)){const v=line.trim();if(!v)continue;total+=v.length;if(v.length>200||/[<>\r\n\u0000-\u001f\u007f\u2028\u2029]/u.test(v))throw new Error('A keyword is too long or contains unsupported characters.');const k=v.toLowerCase();if(!seen.has(k)){seen.add(k);out.push(v)}if(out.length>200||total>8000)throw new Error('Keyword guidance is too large.')}return out}
function readSettings(validate=true){const model=UI.modelSelect.value,m=MODELS[model];if(!m)throw new Error('Select a supported completed-file transcription model.');const languages=languageList(UI.languageInput.value,model,m.languages);const keywords=m.keywords?keywordList(UI.keywordsInput.value):[];let prompt=m.prompt?UI.promptInput.value.trim():'';if(prompt.length>12000)throw new Error('Prompt is too long.');const settings={model,languages,keywords,prompt,chunkMb:strictUiNumber(UI.chunkRange.value,5,24,{integer:true,label:'Chunk size'}),maxMinutes:strictUiNumber(UI.durationRange.value,3,5,{integer:true,label:'Maximum chunk duration'}),retryCount:strictUiNumber(UI.retrySelect.value,0,3,{integer:true,label:'Automatic retry count'}),previousContext:m.previous&&UI.previousContext.checked,includeTimestamps:UI.includeTimestamps.checked,exportTxt:UI.exportTxt.checked,exportMd:UI.exportMd.checked,mergeFiles:UI.mergeFiles.checked,continueOnError:UI.continueOnError.checked,diarize:m.diarize};if(validate&&!settings.exportTxt&&!settings.exportMd)throw new Error('Select at least one transcript download format.');if(validate&&settings.mergeFiles&&state.queue.filter(preparedQueueItem).length>MAX_COMBINED_FILES)throw new Error(`Combined export is limited to ${MAX_COMBINED_FILES.toLocaleString()} queued files. Disable merging or split the queue into smaller runs.`);return settings}
function updateSettingsAvailability(){const m=MODELS[UI.modelSelect.value],locked=state.running;UI.modelSelect.disabled=locked;UI.languageInput.disabled=locked||!m||m.languages==='none';UI.keywordsInput.disabled=locked||!m?.keywords;UI.promptInput.disabled=locked||!m?.prompt;UI.previousContext.disabled=locked||!m?.previous;for(const el of [UI.chunkRange,UI.durationRange,UI.retrySelect,UI.includeTimestamps,UI.exportTxt,UI.exportMd,UI.mergeFiles,UI.continueOnError])el.disabled=locked}
function syncSettingsUi(){const m=MODELS[UI.modelSelect.value];UI.modelHelp.textContent=m?.help||'';updateSettingsAvailability();UI.chunkLabel.textContent=`${UI.chunkRange.value} MB`;UI.durationLabel.textContent=`${UI.durationRange.value} min`;savePrefs();if(!state.running&&state.queue.some(x=>x.status==='done'&&Array.isArray(x.parts)))prepareDownloads(readSettings(false));renderStats()}

function renderStats(){updateSettingsAvailability();UI.fileCountStat.textContent=String(state.queue.length);const dur=state.queue.reduce((s,x)=>s+(x.duration||0),0);UI.durationStat.textContent=secondsText(dur);let price=0;const m=MODELS[UI.modelSelect.value];if(m)price=dur/60*m.price;const derived=m?.priceBasis==='derived_same_audio_token_rates';UI.costEstimate.textContent=`${derived?'Approx.':'Estimated'} ${money(price)}`;UI.costEstimate.title=derived?`Derived estimate only · OpenAI currently publishes diarization audio-token rates rather than a direct per-minute estimate · pricing checked 2026-08-10`:`Estimate only · OpenAI per-minute pricing last verified 2026-08-10 · ${m?.price??0} USD/minute`;UI.startBtn.disabled=state.running||!state.keyConfigured||!state.principalScope||!state.queue.some(eligibleQueueItem)||state.queue.some(x=>x.status==='inspecting');UI.cancelBtn.disabled=!state.running;UI.clearQueueBtn.disabled=state.running||state.queue.length===0;UI.addFilesBtn.disabled=state.running;UI.configureKeyBtn.disabled=state.running;UI.testKeyBtn.disabled=!state.keyConfigured||state.running;UI.forgetKeyBtn.disabled=!state.keyConfigured||state.running}
function renderQueue(){UI.queueEmpty.hidden=state.queue.length>0;UI.queueList.replaceChildren();for(const item of state.queue){const li=document.createElement('li');li.dataset.id=item.id;const main=document.createElement('div');main.className='queue-item-main';const n=document.createElement('strong');const displayName=safeDisplayName(item.file.name);n.textContent=displayName;const meta=document.createElement('span');meta.className='muted';meta.textContent=item.status==='inspecting'?'Inspecting safely…':item.error?`Error: ${item.error}`:`${secondsText(item.duration)} · ${(item.file.size/1_000_000).toFixed(2)} MB · ${item.chunkCount||'?'} chunk${item.chunkCount===1?'':'s'}`;main.append(n,meta);const side=document.createElement('div');side.className='queue-item-actions';const badge=document.createElement('span');badge.className=`mini-state ${item.status||'ready'}`;badge.textContent=item.status==='done'?'Completed':item.status==='error'?'Needs attention':item.status==='running'?'Transcribing':item.status==='inspecting'?'Inspecting':'Ready';const rm=document.createElement('button');rm.type='button';rm.className='icon-btn';rm.setAttribute('aria-label',`Remove ${displayName}`);rm.textContent='×';rm.disabled=state.running;rm.addEventListener('click',()=>{state.queue=state.queue.filter(x=>x.id!==item.id);state.completedFiles=state.queue.filter(x=>x.status==='done').length;UI.completedStat.textContent=String(state.completedFiles);prepareDownloads(readSettings(false));renderQueue()});side.append(badge,rm);li.append(main,side);UI.queueList.append(li)}renderStats()}
async function prepareFile(file,item){try{if(!(file instanceof File)||file.size===0)throw new Error('File is empty.');if(!/\.mp3$/i.test(file.name)&&file.type!=='audio/mpeg'&&file.type!=='audio/mp3')throw new Error('Cosmic Transcriber Web V1 accepts MP3 files only.');const settings=readSettings(false);const [fingerprint,inspection]=await Promise.all([hashBlobStreaming(file,p=>{if(item.status==='inspecting')setProgress(p*12,'Inspecting files',`Hashing ${safeDisplayName(file.name)} in bounded slices…`)}),inspectAndChunkMp3(file,{targetBytes:settings.chunkMb*1_000_000,maxMinutes:settings.maxMinutes,diarize:settings.diarize})]);for(let i=0;i<inspection.chunks.length;i++){const c=inspection.chunks[i];c.sha256=await hashBlobStreaming(materializeChunk(file,c));if(item.status==='inspecting')setProgress(12+((i+1)/inspection.chunks.length)*3,'Inspecting files',`Hashing ${safeDisplayName(file.name)} · prepared Part ${i+1} of ${inspection.chunks.length}…`)}const duplicate=state.queue.find(x=>x!==item&&x.fingerprint===fingerprint&&x.file.size===file.size);if(duplicate)throw new Error('Duplicate content skipped. This audio is already in the queue.');Object.assign(item,{fingerprint,inspection,inspectionKey:`${settings.chunkMb}|${settings.maxMinutes}|${settings.diarize?'d':'n'}`,duration:inspection.duration,chunkCount:inspection.chunks.length,status:'ready',error:null});addDiag('file_prepared',{size:file.size,duration:inspection.duration,chunks:inspection.chunks.length});renderQueue()}catch(e){if(state.queue.includes(item)){item.status='error';item.error=safeError(e);renderQueue()}addDiag('file_prepare_error',{code:errorCode(e)})}}
function naturalFileCompare(a,b){return a.file.name.localeCompare(b.file.name,undefined,{numeric:true,sensitivity:'base'})}
async function addFiles(files){if(state.running)return;const remaining=Math.max(0,MAX_QUEUE_FILES-state.queue.length);if(remaining===0){setProgress(0,'Queue limit reached',`The queue is limited to ${MAX_QUEUE_FILES.toLocaleString()} files.`);return}const list=[];let truncated=false;for(const file of files||[]){if(!file)continue;if(list.length>=remaining){truncated=true;break}list.push(file)}list.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));for(const file of list){const exact=state.queue.find(x=>x.file===file);if(exact)continue;const item={id:rid('q'),file,status:'inspecting',duration:0,chunkCount:0,error:null};state.queue.push(item);renderQueue();await prepareFile(file,item)}state.queue.sort(naturalFileCompare);renderQueue();setProgress(0,truncated?'Queue limit applied':'Ready',truncated?`Only the first ${remaining.toLocaleString()} candidates were inspected because the queue is limited to ${MAX_QUEUE_FILES.toLocaleString()} files.`:state.queue.length?'Review settings, then start transcription.':'Add MP3 files and configure your API key.')}

async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});let body=null;try{body=await response.json()}catch{body={ok:false,error:{code:'malformed_response',message:'The server returned a malformed response.'}}}if(!response.ok||body?.ok===false){const e=new Error(body?.error?.message||`Request failed (${response.status}).`);e.code=body?.error?.code||`http_${response.status}`;e.status=response.status;e.details=body?.error?.details||{};e.requestId=body?.requestId||body?.error?.requestId||null;throw e}return body}
async function refreshSession(){try{const r=await api('/api/session/status');state.keyConfigured=!!r.configured;state.keyExpiresAt=r.expiresAt||null;state.principalScope=typeof r.principalScope==='string'&&/^[A-Za-z0-9_-]{32}$/.test(r.principalScope)?r.principalScope:null;if(state.keyConfigured&&state.principalScope){const mins=Math.max(0,Math.floor((r.expiresAt-Date.now()/1000)/60));UI.keyStatus.textContent=`Configured · ~${mins} min session`;setStatus(state.online?'Authenticated':'Offline',state.online?'good':'warn')}else if(state.keyConfigured){UI.keyStatus.textContent='Session unavailable';setStatus('Authentication scope unavailable','warn')}else if(state.principalScope){UI.keyStatus.textContent='Not configured';setStatus('Authenticated · API key needed','neutral')}else{UI.keyStatus.textContent='Unavailable';setStatus('Access authentication required','warn')}renderStats()}catch(e){state.keyConfigured=false;state.principalScope=null;UI.keyStatus.textContent='Unavailable';setStatus('Access authentication required','warn');setProgress(0,'Authentication needed',safeError(e));addDiag('session_status_error',{code:errorCode(e),status:e.status});renderStats()}}

function settingsForIdentity(s){return {model:s.model,languages:s.languages,keywords:s.keywords,prompt:s.prompt,chunkMb:s.chunkMb,maxMinutes:s.maxMinutes,previousContext:s.previousContext}}
function encodeMetadata(meta){const bytes=new TextEncoder().encode(JSON.stringify(meta));let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function newCheckpoint(item,cpid,sid){return {id:cpid,principalScope:state.principalScope,sourceFingerprint:item.fingerprint,sourceSize:item.file.size,settingsIdentity:sid,chunkerRevision:MP3_CHUNKER_REVISION,chunks:item.inspection.chunks.map(c=>({index:c.index,sourceStart:c.sourceStart,sourceEnd:c.sourceEnd,bytes:c.bytes,sha256:c.sha256,logicalStart:c.logicalStart,duration:c.duration,prerollDuration:c.prerollDuration,status:'pending',attempts:[]})),results:{},createdAt:nowIso()}}
function wait(ms,signal){return new Promise((res,rej)=>{const t=setTimeout(res,ms);signal?.addEventListener('abort',()=>{clearTimeout(t);rej(new DOMException('Aborted','AbortError'))},{once:true})})}
function askAmbiguousRetry(){UI.confirmText.textContent='The previous audio upload may have reached OpenAI. Retrying could create a second transcription charge. Retry only if you accept that risk.';UI.confirmDialog.showModal();return new Promise(resolve=>{state.confirmResolver=resolve})}

function checkpointPersistenceFailure(code,message,billingState,cause){const e=new Error(message);e.code=code;e.details={billingState};e.cause=cause;return e}
async function sendChunk(item,chunk,s,jobId,fileId,previousText,cp){
 let explicit429Retries=0;
 while(true){
  if(state.cancelRequested)throw new DOMException('Cancelled','AbortError');
  const attemptId=rid('attempt');
  const blob=materializeChunk(item.file,chunk);
  const freshChunkHash=await hashBlobStreaming(blob);
  if(freshChunkHash!==chunk.sha256||freshChunkHash!==cp.chunks[chunk.index-1].sha256)throw new Error(`Prepared Part ${chunk.index} changed before dispatch. Transcription stopped before this OpenAI request.`);
  const model=MODELS[s.model];
  const prompt=model.prompt?(s.previousContext?finalPrompt(s.prompt,previousText):s.prompt):'';
  const meta={v:1,jobId,fileId,chunkIndex:chunk.index,chunkCount:item.inspection.chunks.length,attemptId,declaredBytes:blob.size,durationSeconds:Math.max(0.001,chunk.duration+chunk.prerollDuration),model:s.model,languages:s.languages,keywords:model.keywords?s.keywords:[],prompt,requestKind:'transcription'};
  const controller=new AbortController();state.abort=controller;
  const attemptRecord={attemptId,startedAt:nowIso(),state:'dispatched'};
  const chunkRecord=cp.chunks[chunk.index-1];
  chunkRecord.status='in_flight';chunkRecord.attempts=[...(chunkRecord.attempts||[]),attemptRecord];
  try{
   try{await saveCheckpoint(cp)}catch(storageError){attemptRecord.completedAt=nowIso();attemptRecord.state='failed';attemptRecord.code='checkpoint_persist_before_dispatch_failed';chunkRecord.status='pending';addDiag('checkpoint_write_failure_before_dispatch',{chunk:chunk.index});throw checkpointPersistenceFailure('checkpoint_persist_before_dispatch_failed','The checkpoint could not be saved before upload, so no OpenAI request was sent. This run was stopped until browser storage is working reliably.','not_dispatched',storageError)}
   try{
    const r=await api('/api/transcribe',{method:'POST',headers:{'Content-Type':'audio/mpeg','X-Cosmic-Metadata':encodeMetadata(meta)},body:blob,signal:controller.signal});
    let normalized;try{normalized=normalizeOpenAiResult(r.result,chunk)}catch(parseError){throw completedResultValidationError(parseError)}
    attemptRecord.state='success';attemptRecord.completedAt=nowIso();attemptRecord.appRequestId=r.diagnostics?.appRequestId||null;attemptRecord.openaiRequestId=r.diagnostics?.openaiRequestId||null;
    cp.results[chunk.index]={index:chunk.index,logicalStart:chunk.logicalStart,duration:chunk.duration,text:normalized.text,segments:normalized.segments,diagnostics:{appRequestId:attemptRecord.appRequestId,openaiRequestId:attemptRecord.openaiRequestId,status:200},attempts:chunkRecord.attempts};chunkRecord.status='completed';
    try{await saveCheckpoint(cp)}catch(storageError){throw checkpointPersistenceFailure('checkpoint_persist_after_success_failed','OpenAI returned a completed transcription, but its checkpoint could not be saved. This run was stopped to avoid repeating billable work. Fix browser storage before retrying; reloading may discard this completed result.','completed_response_not_durable',storageError)}
    addDiag('chunk_success',{chunk:chunk.index,status:200,openaiRequestId:attemptRecord.openaiRequestId});return cp.results[chunk.index]
   }catch(e){
    if(e?.code==='checkpoint_persist_after_success_failed'){addDiag('checkpoint_write_failure_after_success',{chunk:chunk.index,appRequestId:attemptRecord.appRequestId,openaiRequestId:attemptRecord.openaiRequestId});throw e}
    const aborted=controller.signal.aborted||e?.name==='AbortError';const billingAmbiguous=aborted||ambiguousPaidFailure(e);
    attemptRecord.completedAt=nowIso();attemptRecord.state=billingAmbiguous?'cancelled_or_ambiguous':'failed';attemptRecord.code=errorCode(e);attemptRecord.appRequestId=typeof e?.requestId==='string'?e.requestId.slice(0,160):null;attemptRecord.openaiRequestId=typeof e?.details?.openaiRequestId==='string'?e.details.openaiRequestId.slice(0,160):null;chunkRecord.status=billingAmbiguous?'ambiguous':'pending';
    try{await saveCheckpoint(cp)}catch(storageError){addDiag('checkpoint_write_failure_after_dispatch',{chunk:chunk.index,billingRisk:billingAmbiguous?'ambiguous':'classified',appRequestId:attemptRecord.appRequestId,openaiRequestId:attemptRecord.openaiRequestId});throw checkpointPersistenceFailure('checkpoint_persist_after_dispatch_failed',billingAmbiguous?'The request may have reached OpenAI, but the updated billing-safety checkpoint could not be saved. This run was stopped. Do not retry until browser storage is working; a retry could create a second charge.':'The upstream request was rejected, but the updated checkpoint could not be saved. This run was stopped until browser storage is working reliably.',billingAmbiguous?'ambiguous_checkpoint_not_durable':'classified_failure_checkpoint_not_durable',storageError)}
    addDiag('chunk_failure',{chunk:chunk.index,code:errorCode(e),status:e.status,billingRisk:ambiguousPaidFailure(e)?'ambiguous':'classified',appRequestId:attemptRecord.appRequestId,openaiRequestId:attemptRecord.openaiRequestId});
    if(aborted)throw e;
    if(knownSafeRetry(e)&&explicit429Retries<s.retryCount){const delay=automaticRetryDelayMs(e,explicit429Retries+1);if(delay!==null){explicit429Retries++;await wait(delay,controller.signal);continue}}
    if(ambiguousPaidFailure(e)){const yes=await askAmbiguousRetry();if(yes)continue}
    throw e
   }
  }finally{if(state.abort===controller)state.abort=null}
 }
}

async function ensureInspectionForSettings(item,s){const wanted=`${s.chunkMb}|${s.maxMinutes}|${s.diarize?'d':'n'}`;if(item.inspectionKey===wanted&&item.inspection&&item.inspection.chunks.every(c=>/^[0-9a-f]{64}$/.test(c.sha256||'')))return;item.status='inspecting';renderQueue();const inspection=await inspectAndChunkMp3(item.file,{targetBytes:s.chunkMb*1_000_000,maxMinutes:s.maxMinutes,diarize:s.diarize,onProgress:p=>setProgress(Math.min(8,p*8),'Preparing chunks',`${safeDisplayName(item.file.name)} · validating frame boundaries…`)});for(let i=0;i<inspection.chunks.length;i++){const c=inspection.chunks[i];c.sha256=await hashBlobStreaming(materializeChunk(item.file,c));setProgress(8+((i+1)/inspection.chunks.length)*2,'Preparing chunks',`${safeDisplayName(item.file.name)} · hashing Part ${i+1} of ${inspection.chunks.length}…`)}Object.assign(item,{inspection,inspectionKey:wanted,duration:inspection.duration,chunkCount:inspection.chunks.length,status:'ready',error:null});renderQueue()}

async function processFile(item,s,filePosition,totalFiles){setProgress(((filePosition-1)/totalFiles)*100,`File ${filePosition} of ${totalFiles}`,`Re-verifying source integrity before any billable request…`);const freshFingerprint=await hashBlobStreaming(item.file);if(freshFingerprint!==item.fingerprint)throw new Error('The source file changed after it was added. Transcription was stopped before any OpenAI request. Remove and re-add the file.');await ensureInspectionForSettings(item,s);item.status='running';item.error=null;renderQueue();const sid=await settingsIdentity(settingsForIdentity(s),MP3_CHUNKER_REVISION);if(!state.principalScope)throw new Error('Authenticated checkpoint identity is unavailable. Refresh the page and sign in again before transcription.');const cpid=await checkpointId(state.principalScope,item.fingerprint,sid);let cp=null;try{cp=await loadCheckpoint(cpid)}catch(e){addDiag('checkpoint_corrupt',{code:errorCode(e)});throw new Error('A saved checkpoint is corrupt and was not reused. Remove it in browser site data or change settings to create a fresh job.')}if(cp&&!compatibleCheckpoint(cp,{principalScope:state.principalScope,sourceFingerprint:item.fingerprint,sourceSize:item.file.size,settingsIdentity:sid,chunkerRevision:MP3_CHUNKER_REVISION,chunks:item.inspection.chunks}))throw new Error('Saved checkpoint does not exactly match this source and settings. Resume was refused.');if(!cp)cp=newCheckpoint(item,cpid,sid);const jobId=rid('job'),fileId=rid('file');const parts=[];let previous='',chainReusable=true,transcriptCharacters=0;
 for(let i=0;i<item.inspection.chunks.length;i++){const chunk=item.inspection.chunks[i];if(state.cancelRequested)throw new DOMException('Cancelled','AbortError');const pct=((filePosition-1)+(i/item.inspection.chunks.length))/totalFiles*100;setProgress(pct,`File ${filePosition} of ${totalFiles}`,`${safeDisplayName(item.file.name)} · Part ${chunk.index} of ${item.inspection.chunks.length}`);const cached=cp.results?.[chunk.index];const savedStatus=cp.chunks?.[chunk.index-1]?.status;if(checkpointResultReusable({status:savedStatus,hasResult:!!cached,previousContext:s.previousContext,chainReusable})){transcriptCharacters=addTranscriptCharacters(transcriptCharacters,cached.text,{label:`The transcript for ${item.file.name}`});parts.push(cached);previous=cached.text||'';continue}chainReusable=false;if(cached)delete cp.results[chunk.index];if(checkpointAttemptNeedsConfirmation(savedStatus)){const yes=await askAmbiguousRetry();if(!yes)throw new Error(`Part ${chunk.index} has an unresolved prior upload attempt. It was not resent without explicit confirmation.`)}const part=await sendChunk(item,chunk,s,jobId,fileId,previous,cp);transcriptCharacters=addTranscriptCharacters(transcriptCharacters,part.text,{label:`The transcript for ${item.file.name}`});parts.push(part);previous=part.text||'';if(state.cancelRequested)throw new DOMException('Cancelled','AbortError')}
 item.parts=parts;item.completedSettingsIdentity=sid;item.status='done';item.error=null;state.completedFiles++;UI.completedStat.textContent=String(state.completedFiles);renderQueue();return parts}

function prepareDownloads(s){state.downloads=[];const done=state.queue.filter(x=>x.status==='done'&&Array.isArray(x.parts));for(const item of done){const base=safeBaseName(item.file.name);if(s.exportTxt)state.downloads.push({name:`${base}.txt`,makeText:()=>buildFileOutput(item.file.name,item.parts,{includeTimestamps:s.includeTimestamps,markdown:false}),type:'text/plain;charset=utf-8'});if(s.exportMd)state.downloads.push({name:`${base}.md`,makeText:()=>buildFileOutput(item.file.name,item.parts,{includeTimestamps:s.includeTimestamps,markdown:true}),type:'text/markdown;charset=utf-8'})}const mixedSettings=s.mergeFiles&&combinedExportHasMixedSettings(state.queue);if(s.mergeFiles&&combinedExportComplete(state.queue)&&combinedTranscriptWithinLimit(done)){if(s.exportTxt)state.downloads.push({name:'Combined Transcript.txt',makeText:()=>done.map(x=>buildFileOutput(x.file.name,x.parts,{includeTimestamps:s.includeTimestamps,markdown:false})).join('\n\n'),type:'text/plain;charset=utf-8'});if(s.exportMd)state.downloads.push({name:'Combined Transcript.md',makeText:()=>done.map(x=>buildFileOutput(x.file.name,x.parts,{includeTimestamps:s.includeTimestamps,markdown:true})).join('\n\n'),type:'text/markdown;charset=utf-8'})}renderDownloads();return {mixedSettings}}
function renderDownloads(){UI.downloadButtons.replaceChildren();for(const d of state.downloads){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=`Download ${d.name}`;b.addEventListener('click',()=>{try{downloadText(d.name,d.makeText(),d.type)}catch(e){setProgress(Number(UI.progressBar.value),'Could not prepare download',safeError(e))}});UI.downloadButtons.append(b)}UI.downloads.hidden=state.downloads.length===0}
async function run(){if(state.running)return;let s;try{s=readSettings(true)}catch(e){setProgress(0,'Check settings',safeError(e));return}if(!state.keyConfigured){setProgress(0,'API key needed','Configure your own OpenAI API key first.');return}if(!state.principalScope){setProgress(0,'Authentication scope unavailable','Refresh the page and sign in through Cloudflare Access again before starting.');return}const ready=state.queue.filter(eligibleQueueItem);if(!ready.length){setProgress(0,'No usable files','Add at least one valid MP3.');return}state.running=true;state.cancelRequested=false;state.completedFiles=state.queue.filter(x=>x.status==='done').length;UI.completedStat.textContent=String(state.completedFiles);state.downloads=[];renderDownloads();renderStats();window.addEventListener('beforeunload',beforeUnload);addDiag('job_started',{files:ready.length,model:s.model});let failed=0;
 try{for(let i=0;i<ready.length;i++){try{await processFile(ready[i],s,i+1,ready.length)}catch(e){if(e?.name==='AbortError'||state.cancelRequested)throw e;ready[i].status='error';ready[i].error=safeError(e);failed++;renderQueue();setProgress((i+1)/ready.length*100,'File failed',safeError(e));if(systemicJobFailure(e)||!s.continueOnError)throw e}}const outputState=prepareDownloads(s);const mergeNote=outputState.mixedSettings?' Combined transcript was withheld because completed files used different transcription settings.':'';setProgress(100,state.cancelRequested?'Cancelled':failed?'Finished with errors':'Complete',(failed?`${ready.length-failed} file(s) completed; ${failed} need attention.`:`${ready.length} file(s) completed. Downloads are ready.`)+mergeNote);addDiag('job_finished',{completed:ready.length-failed,failed,mixedSettings:outputState.mixedSettings})}
 catch(e){prepareDownloads(s);if(e?.name==='AbortError'||state.cancelRequested){for(const item of state.queue)if(item.status==='running'){item.status='ready';item.error=null}renderQueue();setProgress(Number(UI.progressBar.value),'Cancelled','No additional chunks will start. Completed files remain downloadable and completed chunks remain checkpointed. A request cancelled after dispatch may still have reached OpenAI and may still be billed.');addDiag('job_cancelled',{})}else{setProgress(Number(UI.progressBar.value),'Stopped',safeError(e));addDiag('job_stopped',{code:errorCode(e),status:e.status})}}
 finally{state.running=false;state.abort=null;window.removeEventListener('beforeunload',beforeUnload);renderStats();renderQueue();await refreshSession()}}
function beforeUnload(e){if(!state.running)return;e.preventDefault();e.returnValue=''}

function diagnosticsText(){const settings=readSettings(false);const data={schema:'cosmic-web-diagnostics-1',appVersion:APP_VERSION,desktopBehavioralBaseline:'1.0.27',generatedAt:nowIso(),browser:{userAgent:navigator.userAgent,language:navigator.language,online:navigator.onLine},session:{configured:state.keyConfigured,expiresAt:state.keyExpiresAt},settings:{model:settings.model,languageHintCount:settings.languages.length,keywordCount:settings.keywords.length,chunkMb:settings.chunkMb,maxMinutes:settings.maxMinutes,previousContext:settings.previousContext,includeTimestamps:settings.includeTimestamps},queue:state.queue.map(x=>({size:x.file.size,duration:x.duration||0,chunks:x.chunkCount||0,status:x.status,errorCode:x.error?'client_error':null})),events:state.diagnostics};return JSON.stringify(data,null,2)+'\n'}

function closeKeyDialog(){UI.apiKeyInput.value='';UI.keyDialogError.textContent='';if(UI.keyDialog.open)UI.keyDialog.close()}
UI.configureKeyBtn.addEventListener('click',()=>{UI.keyDialogError.textContent='';UI.apiKeyInput.value='';UI.keyDialog.showModal();setTimeout(()=>UI.apiKeyInput.focus(),0)});
UI.cancelKeyBtn.addEventListener('click',closeKeyDialog);UI.closeKeyBtn.addEventListener('click',closeKeyDialog);UI.keyDialog.addEventListener('cancel',e=>{e.preventDefault();closeKeyDialog()});
UI.keyForm.addEventListener('submit',async e=>{e.preventDefault();const value=UI.apiKeyInput.value;UI.keyDialogError.textContent='';try{if(!value||value.length>512||/[\s\u0000-\u001f\u007f]/u.test(value))throw new Error('Enter the API key exactly as issued by OpenAI, without spaces.');await api('/api/key/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:value})});UI.apiKeyInput.value='';UI.keyDialog.close();await refreshSession();setProgress(0,'Ready','Secure API-key session configured.')}catch(err){UI.keyDialogError.textContent=safeError(err)}finally{UI.apiKeyInput.value=''}});
UI.testKeyBtn.addEventListener('click',async()=>{if(!confirm('This uses a tiny 0.25-second silent MP3 to test actual transcription permission and may incur minimal OpenAI API usage. Continue?'))return;UI.testKeyBtn.disabled=true;try{setProgress(0,'Testing API access','Sending the disclosed tiny transcription request…');const r=await api('/api/key/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmMinimalUsage:true})});setProgress(0,'API access confirmed',`OpenAI transcription permission works${r.diagnostics?.openaiRequestId?` · request ${r.diagnostics.openaiRequestId}`:''}.`);addDiag('key_test_success',{openaiRequestId:r.diagnostics?.openaiRequestId})}catch(e){setProgress(0,'API access test failed',safeError(e));addDiag('key_test_failure',{code:errorCode(e),status:e.status})}finally{renderStats()}});
UI.forgetKeyBtn.addEventListener('click',async()=>{try{await api('/api/key/forget',{method:'DELETE'});state.keyConfigured=false;state.keyExpiresAt=null;state.principalScope=null;UI.keyStatus.textContent='Not configured';setProgress(0,'API key forgotten','This browser credential cookie was cleared. If compromise is suspected, revoke or rotate the key at OpenAI.');renderStats()}catch(e){setProgress(0,'Could not clear session',safeError(e))}});
UI.addFilesBtn.addEventListener('click',()=>UI.fileInput.click());UI.fileInput.addEventListener('change',async()=>{await addFiles(UI.fileInput.files);UI.fileInput.value=''});UI.dropZone.addEventListener('click',()=>UI.fileInput.click());UI.dropZone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();UI.fileInput.click()}});for(const ev of ['dragenter','dragover'])UI.dropZone.addEventListener(ev,e=>{e.preventDefault();UI.dropZone.classList.add('dragging')});for(const ev of ['dragleave','drop'])UI.dropZone.addEventListener(ev,e=>{e.preventDefault();UI.dropZone.classList.remove('dragging')});UI.dropZone.addEventListener('drop',e=>addFiles(e.dataTransfer?.files||[]));UI.clearQueueBtn.addEventListener('click',()=>{if(state.running)return;state.queue=[];state.completedFiles=0;UI.completedStat.textContent='0';state.downloads=[];renderDownloads();renderQueue();setProgress(0,'Ready','Queue and in-memory transcript downloads cleared. Saved checkpoints remain available for safe resume.')});
for(const el of [UI.modelSelect,UI.languageInput,UI.chunkRange,UI.durationRange,UI.retrySelect,UI.keywordsInput,UI.promptInput,UI.previousContext,UI.includeTimestamps,UI.exportTxt,UI.exportMd,UI.mergeFiles,UI.continueOnError])el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'||el.type==='range'?'change':'input',syncSettingsUi);
UI.startBtn.addEventListener('click',run);UI.cancelBtn.addEventListener('click',()=>{state.cancelRequested=true;state.abort?.abort('user cancellation');if(state.confirmResolver){const resolve=state.confirmResolver;state.confirmResolver=null;if(UI.confirmDialog.open)UI.confirmDialog.close();resolve(false)}UI.cancelBtn.disabled=true;UI.progressDetail.textContent='Cancellation requested. No additional chunks will start.'});
UI.confirmYes.addEventListener('click',()=>{UI.confirmDialog.close();state.confirmResolver?.(true);state.confirmResolver=null});UI.confirmNo.addEventListener('click',()=>{UI.confirmDialog.close();state.confirmResolver?.(false);state.confirmResolver=null});UI.confirmDialog.addEventListener('cancel',e=>{e.preventDefault();UI.confirmDialog.close();const resolve=state.confirmResolver;state.confirmResolver=null;resolve?.(false)});
UI.themeBtn.addEventListener('click',()=>{const paper=document.documentElement.dataset.theme!=='paper';document.documentElement.dataset.theme=paper?'paper':'night';UI.themeBtn.textContent=paper?'Cosmic Night':'Cosmic Paper';savePrefs()});UI.aboutBtn.addEventListener('click',()=>UI.aboutDialog.showModal());UI.closeAboutBtn.addEventListener('click',()=>UI.aboutDialog.close());UI.diagnosticsBtn.addEventListener('click',()=>downloadText(`cosmic-transcriber-web-${APP_VERSION}-diagnostics.json`,diagnosticsText(),'application/json;charset=utf-8'));
window.addEventListener('offline',()=>{state.online=false;setStatus('Offline','warn');if(state.running)UI.progressDetail.textContent='Network connection lost. Completed checkpoints are preserved.'});window.addEventListener('online',()=>{state.online=true;setStatus(state.keyConfigured?'Authenticated':'Online','good')});

UI.versionText.textContent=`v${APP_VERSION}`;initSettings();renderQueue();refreshSession();
// CTW_RESTORED_KEYWORD_SEMANTICS
{
  const ctwSemanticPreferenceKey = "cosmic-transcriber-web-preferences-v1";
  const ctwRepairSemanticKeywords = () => {
    const ctwSemanticKeywordsInput = document.getElementById("keywordsInput");
    if (!ctwSemanticKeywordsInput) return;
    const ctwKeywordCandidate = ctwSemanticKeywordsInput.value;
    let ctwKeywordSafe = ctwKeywordCandidate;
    try {
      keywordList(ctwKeywordCandidate);
    } catch {
      ctwKeywordSafe = "";
    }
    if (ctwKeywordSafe === ctwKeywordCandidate) return;
    ctwSemanticKeywordsInput.value = ctwKeywordSafe;
    try {
      const ctwSemanticRaw = localStorage.getItem(ctwSemanticPreferenceKey);
      if (ctwSemanticRaw === null) return;
      const ctwSemanticParsed = JSON.parse(ctwSemanticRaw);
      if (!ctwSemanticParsed || typeof ctwSemanticParsed !== "object" || Array.isArray(ctwSemanticParsed)) return;
      if (typeof ctwSemanticParsed.keywords !== "string" || ctwSemanticParsed.keywords === ctwKeywordSafe) return;
      ctwSemanticParsed.keywords = ctwKeywordSafe;
      localStorage.setItem(ctwSemanticPreferenceKey, JSON.stringify(ctwSemanticParsed));
    } catch {}
  };
  if (document.readyState === "complete") ctwRepairSemanticKeywords();
  else window.addEventListener("load", ctwRepairSemanticKeywords, { once: true });
}
